version: '2.2'

services:
  frontend:
    image: spotify
    build: .
    ports:
      - "3030:3030"
    restart: on-failure
    container_name: spotify
    volumes:
      - .:/app
      - /app/node_modules